spring:
  application:
    name: config-server
  profiles:
    active: native

server.port: 8888

spring.cloud.config.server.native.searchLocations: file:C:/git/DidYouWatch/config-server/config-repo/

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging.level.root: debug

app.auth-server: localhost

---
spring.config.activate.on-profile: prod

spring.cloud.config.server.native.searchLocations: file:${PWD}/config-repo

management.endpoints.web.exposure.include: health, info

logging.level.root: info

app.auth-server: auth-server
