apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
      version: 'v1'
  template:
    metadata:
      labels:
        app: config-server
        version: 'v1'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - config-server
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: config-server
          image: gcr.io/didyouwatch-329208/config-server
          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: prod
#            - name: JAVA_OPTS
#              value: ' -Xmx256m -Xms256m -DSpring.profiles.active=${SPRING_PROFILES_ACTIVE}'
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '512Mi'
              cpu: '250m'
          ports:
            - name: http
              containerPort: 8888
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 120
          volumeMounts:
            - name: config-volume
              mountPath: "/config-repo"
      volumes:
        - name: config-volume
          configMap:
            name: config-server-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: config-server-service
  namespace: default
  labels:
    app: config-server-service
spec:
  type: ClusterIP
  selector:
    app: config-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8888
